name: unicef-ecaro-cpe
channels:
  - conda-forge
dependencies:
  - python=3.10  # Install Python via Conda, not pip
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - ipython
  - jupyterlab
  - ploomber
  - pandas
  - openpyxl
  - scikit-learn
  - matplotlib
  - plotly=5.24.1
  - kaleido-core=0.2.1
  - tqdm
  - notebook
  - pyarrow
  - pip:
      - python-dotenv
      - pypdfium2
      - python-docx
      - openai
      - papermill
      - langchain
      - langchain-community
      - langchain-core
      - langchain-text-splitters
      - ollama
      - langchain-ollama
      - langchain-openai
      - pdf2image
      - pytesseract